In [1]:
import numpy as np
import nibabel as nb
import scipy.io
import statsmodels.api as sm
import pandas as pd
from ipynb.fs.full.utils import *

In [2]:
eye_data = scipy.io.loadmat('E:/FPP_files_and_codes/FPP_files/eye_movment_data/final162.mat')

In [3]:
eye_data = eye_data['final162']

In [4]:
eye_data.shape

(1, 3655)

In [5]:
eye_data = eye_data.squeeze(0)

In [6]:
eye_data.shape

(3655,)

In [7]:
shift = 4
eye_data_shifted = np.roll(eye_data, shift)

In [8]:
eye_data_shifted[0:10]

array([49.00642113, 71.04398563, 77.62893563, 56.82734859, 65.92465789,
       48.32658017, 60.78593505, 43.26561335, 63.90311461, 49.93808635])

In [9]:
eye_data[0:10]

array([65.92465789, 48.32658017, 60.78593505, 43.26561335, 63.90311461,
       49.93808635, 43.69327045, 28.87276081, 43.73252546, 45.83300632])

In [10]:
left_data = scipy.io.loadmat('E:/FPP_files_and_codes/FPP_files/Movie_watching_avg_data/notmean_left_Meanfile.mat')['Left_data']
right_data = scipy.io.loadmat('E:/FPP_files_and_codes/FPP_files/Movie_watching_avg_data/notmean_right_Meanfile.mat')['Right_data']

In [11]:
sifted_regressor_eye_data_2d = eye_data_shifted.reshape(1, -1)

X = sifted_regressor_eye_data_2d.T

coefficients_regressor_eye_data_right = np.zeros(32492)

pvalue_coefficients_regressor_eye_data_right = np.zeros(32492)


zero = np.zeros(3655)

for (i,vertex_data) in enumerate(right_data):
    y = vertex_data
    df = pd.DataFrame(X, columns=['X1'])
    df['y'] = y

    X = sm.add_constant(df[['X1']])
    model = sm.GLM(df['y'], X, family=sm.families.Gaussian())

    if not np.array_equal(vertex_data, zero):
        result = model.fit()
        coefficients = result.params

        coefficients_regressor_eye_data_right[i] = coefficients['X1']
        
        p_values = result.pvalues
        pvalue_coefficients_regressor_eye_data_right[i] = p_values['X1']

In [97]:
coefficients_regressor_eye_data_right

array([-7.86690169e-05, -1.89596811e-04, -6.84768430e-05, ...,
       -2.48152099e-05, -1.46855564e-05,  2.03176315e-05])

In [12]:
making_beta_and_sig_map_right(coefficients_regressor_eye_data_right, pvalue_coefficients_regressor_eye_data_right,\
                              'E:/FPP_files_and_codes/FPP_files/eye_movment_maps/beta_regressor_eye_movment_with_constant_shift4.R.func.gii',\
                              'E:/FPP_files_and_codes/FPP_files/eye_movment_maps/significance_beta_regressor_eye_movment_with_constant_shift4.R.func.gii')

e:\FPP_files_and_codes\FPP_codebase\Figure6_analysis\Final_analysis\utils.ipynb:17: RuntimeWarning: divide by zero encountered in log
  "outputs": [],
e:\FPP_files_and_codes\FPP_codebase\Figure6_analysis\Final_analysis\utils.ipynb:17: RuntimeWarning: invalid value encountered in multiply
  "outputs": [],


In [13]:
shifted_regressor_eye_data_2d = eye_data_shifted.reshape(1, -1)

X = shifted_regressor_eye_data_2d.T

coefficients_regressor_eye_data_left = np.zeros(32492)

pvalue_coefficients_regressor_eye_data_left = np.zeros(32492)


zero = np.zeros(3655)

for (i,vertex_data) in enumerate(left_data):
    y = vertex_data
    df = pd.DataFrame(X, columns=['X1'])
    df['y'] = y

    X = sm.add_constant(df[['X1']])
    model = sm.GLM(df['y'], X, family=sm.families.Gaussian())

    if not np.array_equal(vertex_data, zero):
        result = model.fit()
        coefficients = result.params

        coefficients_regressor_eye_data_left[i] = coefficients['X1']
        
        p_values = result.pvalues
        pvalue_coefficients_regressor_eye_data_left[i] = p_values['X1']

In [14]:
making_beta_and_sig_map_left(coefficients_regressor_eye_data_left, pvalue_coefficients_regressor_eye_data_left,\
                              'E:/FPP_files_and_codes/FPP_files/eye_movment_maps/beta_regressor_eye_movment_with_constant_shift4.L.func.gii',\
                              'E:/FPP_files_and_codes/FPP_files/eye_movment_maps/significance_beta_regressor_eye_movment_with_constant_shift4.L.func.gii')

e:\FPP_files_and_codes\FPP_codebase\Figure6_analysis\Final_analysis\utils.ipynb:32: RuntimeWarning: divide by zero encountered in log
  "    temp_r.darrays[0].data = float32_significance_beta\n",
e:\FPP_files_and_codes\FPP_codebase\Figure6_analysis\Final_analysis\utils.ipynb:32: RuntimeWarning: invalid value encountered in multiply
  "    temp_r.darrays[0].data = float32_significance_beta\n",
